version: '3.7'
services:
  pg_pv:
    image: 'postgres:16'
    container_name: 'pg_pv_16'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - '5436:5436'
    command: -p 5436
    volumes:
      - postgres-data-pv:/var/lib/postgresql/data
      - postgres-data-pv:/docker-entrypoint-initdb.d
      - ./sql:/sql
    restart: always
volumes:
  postgres-data-pv:
